name: Code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: action/setup-python@v2
        with:
          python-vrsion: 3.9
      - name: Install deps
        run:
          python -m pip install --upgrade pip
          pip install -r test_main.py
      - name: Run test_main.py
        run:  test_main.py .